language: go

go:
  - 1.3
  - 1.4

install:
  - export GOPATH="$HOME/gopath"
  - mkdir -p "$GOPATH/src/github.com/spiffylabs"
  - mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/github.com/spiffylabs/oauth2"
  - go get -v -t -d -tags='appengine appenginevm' github.com/spiffylabs/oauth2/...

script:
  - go test -v -tags='appengine appenginevm' github.com/spiffylabs/oauth2/...
